<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import * as monitorAPI from '@shared-api/admin/channelMonitor'
import type { ChannelMonitor, CreateParams as CreateMonitorParams, Provider, UpdateParams as UpdateMonitorParams } from '@shared-api/admin/channelMonitor'
import * as templateAPI from '@shared-api/admin/channelMonitorTemplate'
import type { ChannelMonitorTemplate, CreateParams as CreateTemplateParams, UpdateParams as UpdateTemplateParams } from '@shared-api/admin/channelMonitorTemplate'
import ConsoleShell from '@/components/layout/ConsoleShell.vue'
import PageState from '@/components/base/PageState.vue'
import ChannelMonitorEditorDialog from '@/components/admin/monitor/ChannelMonitorEditorDialog.vue'
import ChannelMonitorActivityDialog from '@/components/admin/monitor/ChannelMonitorActivityDialog.vue'
import MonitorTemplateDialog from '@/components/admin/monitor/MonitorTemplateDialog.vue'
import MonitorTemplateApplyDialog from '@/components/admin/monitor/MonitorTemplateApplyDialog.vue'
import { ConfirmTone, useConfirmStore } from '@/stores/confirm'
import { formatResourceDate } from '@/features/admin/resources/model'
import { useAppStore } from '@/stores/app'

enum MonitorTab { MONITORS = 'monitors', TEMPLATES = 'templates' }
const app = useAppStore(); const confirm = useConfirmStore(); const tab = ref(MonitorTab.MONITORS)
const monitors = ref<ChannelMonitor[]>([]); const templates = ref<ChannelMonitorTemplate[]>([]); const total = ref(0); const pages = ref(1); const page = ref(1); const pageSize = ref(20)
const filters = reactive({ search: '', provider: '', enabled: '' }); const templateFilters = reactive({ provider: '', apiMode: '' })
const loading = ref(true); const templatesLoading = ref(false); const error = ref(''); const showMonitorEditor = ref(false); const editingMonitor = ref<ChannelMonitor | null>(null); const monitorSubmitting = ref(false); const activityMonitor = ref<ChannelMonitor | null>(null)
const showTemplateEditor = ref(false); const editingTemplate = ref<ChannelMonitorTemplate | null>(null); const templateSubmitting = ref(false); const applyingTemplate = ref<ChannelMonitorTemplate | null>(null)
let controller: AbortController | null = null; let timer: number | null = null
const operational = computed(() => monitors.value.filter(item => item.primary_status === 'operational').length)
const degraded = computed(() => monitors.value.filter(item => item.primary_status === 'degraded' || item.primary_status === 'failed' || item.primary_status === 'error').length)
const averageAvailability = computed(() => monitors.value.length ? monitors.value.reduce((sum, item) => sum + item.availability_7d, 0) / monitors.value.length : 0)

async function loadMonitors(): Promise<void> { controller?.abort(); controller = new AbortController(); const current = controller; loading.value = true; error.value = ''; try { const response = await monitorAPI.list({ page: page.value, page_size: pageSize.value, search: filters.search.trim() || undefined, provider: (filters.provider || undefined) as Provider | undefined, enabled: filters.enabled === '' ? undefined : filters.enabled === 'true' }, { signal: current.signal }); monitors.value = response.items; total.value = response.total; pages.value = response.pages } catch (caught) { if ((caught as { code?: string }).code !== 'ERR_CANCELED') error.value = (caught as { message?: string }).message || '渠道监控加载失败' } finally { if (controller === current) loading.value = false } }
async function loadTemplates(): Promise<void> { templatesLoading.value = true; try { templates.value = (await templateAPI.list({ provider: (templateFilters.provider || undefined) as Provider | undefined, api_mode: (templateFilters.apiMode || undefined) as 'chat_completions' | 'responses' | undefined })).items } catch (caught) { app.showError((caught as { message?: string }).message || '请求模板加载失败') } finally { templatesLoading.value = false } }
function searchLater(): void { if (timer) window.clearTimeout(timer); timer = window.setTimeout(() => { page.value = 1; void loadMonitors() }, 280) }
function filter(): void { page.value = 1; void loadMonitors() }
function createMonitor(): void { editingMonitor.value = null; showMonitorEditor.value = true }
async function editMonitor(monitor: ChannelMonitor): Promise<void> { try { editingMonitor.value = await monitorAPI.get(monitor.id); showMonitorEditor.value = true } catch (caught) { app.showError((caught as { message?: string }).message || '监控详情加载失败') } }
async function saveMonitor(payload: CreateMonitorParams | UpdateMonitorParams): Promise<void> { if (monitorSubmitting.value) return; monitorSubmitting.value = true; try { if (editingMonitor.value) await monitorAPI.update(editingMonitor.value.id, payload as UpdateMonitorParams); else await monitorAPI.create(payload as CreateMonitorParams); app.showSuccess(editingMonitor.value ? '监控已更新' : '监控已创建'); showMonitorEditor.value = false; await loadMonitors() } catch (caught) { app.showError((caught as { message?: string }).message || '监控保存失败') } finally { monitorSubmitting.value = false } }
async function duplicateMonitor(monitor: ChannelMonitor): Promise<void> { try { await monitorAPI.duplicate(monitor.id); app.showSuccess(`已复制 ${monitor.name}`); await loadMonitors() } catch (caught) { app.showError((caught as { message?: string }).message || '复制失败') } }
async function toggleMonitor(monitor: ChannelMonitor): Promise<void> { try { await monitorAPI.update(monitor.id, { enabled: !monitor.enabled }); app.showSuccess(monitor.enabled ? '监控已停用' : '监控已启用'); await loadMonitors() } catch (caught) { app.showError((caught as { message?: string }).message || '状态更新失败') } }
async function deleteMonitor(monitor: ChannelMonitor): Promise<void> { if (!await confirm.ask({ title: '删除渠道监控', message: `确认删除 ${monitor.name} 及其检查历史？`, confirmText: '删除', tone: ConfirmTone.DANGER })) return; try { await monitorAPI.del(monitor.id); app.showSuccess('监控已删除'); await loadMonitors() } catch (caught) { app.showError((caught as { message?: string }).message || '删除失败') } }
function createTemplate(): void { editingTemplate.value = null; showTemplateEditor.value = true }
async function editTemplate(template: ChannelMonitorTemplate): Promise<void> { try { editingTemplate.value = await templateAPI.get(template.id); showTemplateEditor.value = true } catch (caught) { app.showError((caught as { message?: string }).message || '模板详情加载失败') } }
async function saveTemplate(payload: CreateTemplateParams | UpdateTemplateParams): Promise<void> { if (templateSubmitting.value) return; templateSubmitting.value = true; try { if (editingTemplate.value) await templateAPI.update(editingTemplate.value.id, payload as UpdateTemplateParams); else await templateAPI.create(payload as CreateTemplateParams); app.showSuccess(editingTemplate.value ? '模板已更新' : '模板已创建'); showTemplateEditor.value = false; await loadTemplates() } catch (caught) { app.showError((caught as { message?: string }).message || '模板保存失败') } finally { templateSubmitting.value = false } }
async function deleteTemplate(template: ChannelMonitorTemplate): Promise<void> { if (!await confirm.ask({ title: '删除请求模板', message: `确认删除 ${template.name}？已复制到监控的请求快照不受影响。`, confirmText: '删除', tone: ConfirmTone.DANGER })) return; try { await templateAPI.del(template.id); app.showSuccess('模板已删除'); await loadTemplates() } catch (caught) { app.showError((caught as { message?: string }).message || '删除失败') } }
onMounted(() => { void Promise.all([loadMonitors(), loadTemplates()]) }); onBeforeUnmount(() => { controller?.abort(); if (timer) window.clearTimeout(timer) })
</script>

<template><ConsoleShell><main class="resource-page"><header class="resource-page__heading"><div><span class="resource-eyebrow">Health Checks</span><h1>渠道监控</h1><p>管理真实上游探测、请求快照模板、即时检查与历史可用率；密钥始终使用脱敏与仅写策略。</p></div><button class="resource-button" @click="tab === MonitorTab.MONITORS ? createMonitor() : createTemplate()">{{ tab === MonitorTab.MONITORS ? '创建监控' : '创建模板' }}</button></header>
  <div class="resource-tabs"><button :aria-selected="tab === MonitorTab.MONITORS" @click="tab = MonitorTab.MONITORS">监控任务 · {{ total }}</button><button :aria-selected="tab === MonitorTab.TEMPLATES" @click="tab = MonitorTab.TEMPLATES">请求模板 · {{ templates.length }}</button></div>
  <template v-if="tab === MonitorTab.MONITORS"><section class="resource-summary"><div><span>当前页任务</span><strong>{{ monitors.length }}</strong></div><div><span>运行正常</span><strong>{{ operational }}</strong></div><div><span>异常 / 降级</span><strong>{{ degraded }}</strong></div><div><span>7 日平均可用率</span><strong>{{ averageAvailability.toFixed(2) }}%</strong></div></section><section class="resource-toolbar"><div class="resource-toolbar__filters"><input v-model="filters.search" type="search" placeholder="搜索名称、组名或模型" @input="searchLater" /><select v-model="filters.provider" @change="filter"><option value="">全部提供商</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Gemini</option><option value="grok">Grok</option></select><select v-model="filters.enabled" @change="filter"><option value="">全部启用状态</option><option value="true">启用</option><option value="false">停用</option></select></div><button class="resource-button resource-button--secondary" @click="loadMonitors">刷新</button></section>
  <PageState :loading="loading" :error="error" :empty="!loading && !error && monitors.length === 0" empty-text="没有匹配的监控任务。" @retry="loadMonitors"><div class="resource-table"><table><thead><tr><th>监控</th><th>提供商 / 模式</th><th>主模型</th><th>最新状态</th><th>延迟</th><th>7 日可用率</th><th>周期</th><th>上次检查</th><th>操作</th></tr></thead><tbody><tr v-for="monitor in monitors" :key="monitor.id"><td><strong>{{ monitor.name }}</strong><small>#{{ monitor.id }} · {{ monitor.group_name || '未分组' }}</small></td><td>{{ monitor.provider }}<small>{{ monitor.api_mode }}</small></td><td>{{ monitor.primary_model }}<small>+{{ monitor.extra_models.length }} 个额外模型</small></td><td><span :class="['resource-status', `resource-status--${monitor.primary_status || (monitor.enabled ? 'degraded' : 'disabled')}`]">{{ monitor.primary_status || (monitor.enabled ? '待检查' : '停用') }}</span><small v-if="monitor.api_key_decrypt_failed" class="resource-field-error">密钥需重填</small></td><td>{{ monitor.primary_latency_ms ?? '—' }} ms</td><td>{{ monitor.availability_7d.toFixed(2) }}%</td><td>{{ monitor.interval_seconds }}s<small>± {{ monitor.jitter_seconds }}s</small></td><td>{{ formatResourceDate(monitor.last_checked_at) }}</td><td><div class="resource-inline-actions"><button class="resource-link" @click="activityMonitor = monitor">检查 / 历史</button><button class="resource-link" @click="editMonitor(monitor)">编辑</button><button class="resource-link" @click="duplicateMonitor(monitor)">复制</button><button class="resource-link" @click="toggleMonitor(monitor)">{{ monitor.enabled ? '停用' : '启用' }}</button><button class="resource-link resource-link--danger" @click="deleteMonitor(monitor)">删除</button></div></td></tr></tbody></table></div></PageState><footer class="resource-pagination"><span>共 {{ total }} 条 · 第 {{ page }} / {{ pages }} 页</span><div class="resource-pagination__actions"><select v-model.number="pageSize" @change="page = 1; loadMonitors()"><option :value="20">20 / 页</option><option :value="50">50 / 页</option></select><button class="resource-button resource-button--secondary" :disabled="page <= 1" @click="page--; loadMonitors()">上一页</button><button class="resource-button resource-button--secondary" :disabled="page >= pages" @click="page++; loadMonitors()">下一页</button></div></footer></template>
  <template v-else><section class="resource-toolbar"><div class="resource-toolbar__filters"><select v-model="templateFilters.provider" @change="loadTemplates"><option value="">全部提供商</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Gemini</option><option value="grok">Grok</option></select><select v-model="templateFilters.apiMode" @change="loadTemplates"><option value="">全部 API 模式</option><option value="chat_completions">Chat Completions</option><option value="responses">Responses</option></select></div><button class="resource-button resource-button--secondary" @click="loadTemplates">刷新</button></section><PageState :loading="templatesLoading" :error="''" :empty="!templatesLoading && templates.length === 0" empty-text="暂无请求模板。"><div class="resource-table"><table><thead><tr><th>模板</th><th>提供商 / 模式</th><th>Headers</th><th>Body 覆盖</th><th>关联监控</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr v-for="template in templates" :key="template.id"><td><strong>{{ template.name }}</strong><small>{{ template.description || '无说明' }}</small></td><td>{{ template.provider }}<small>{{ template.api_mode }}</small></td><td>{{ Object.keys(template.extra_headers).length }} 项</td><td>{{ template.body_override_mode }}</td><td>{{ template.associated_monitors }}</td><td>{{ formatResourceDate(template.updated_at) }}</td><td><div class="resource-inline-actions"><button class="resource-link" :disabled="template.associated_monitors === 0" @click="applyingTemplate = template">应用到关联监控</button><button class="resource-link" @click="editTemplate(template)">编辑</button><button class="resource-link resource-link--danger" @click="deleteTemplate(template)">删除</button></div></td></tr></tbody></table></div></PageState></template>
  </main><ChannelMonitorEditorDialog :show="showMonitorEditor" :monitor="editingMonitor" :templates="templates" :submitting="monitorSubmitting" @close="showMonitorEditor = false" @submit="saveMonitor" /><ChannelMonitorActivityDialog :show="Boolean(activityMonitor)" :monitor="activityMonitor" @close="activityMonitor = null" /><MonitorTemplateDialog :show="showTemplateEditor" :template="editingTemplate" :submitting="templateSubmitting" @close="showTemplateEditor = false" @submit="saveTemplate" /><MonitorTemplateApplyDialog :show="Boolean(applyingTemplate)" :template="applyingTemplate" @close="applyingTemplate = null" @applied="loadMonitors" /></ConsoleShell></template>
