<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import * as proxiesAPI from '@shared-api/admin/proxies'
import type { AdminDataPayload, CreateProxyRequest, Proxy, UpdateProxyRequest } from '@/types'
import ConsoleShell from '@/components/layout/ConsoleShell.vue'
import PageState from '@/components/base/PageState.vue'
import ProxyEditorDialog from '@/components/admin/proxies/ProxyEditorDialog.vue'
import ProxyDetailDialog from '@/components/admin/proxies/ProxyDetailDialog.vue'
import ProxyBatchDialog from '@/components/admin/proxies/ProxyBatchDialog.vue'
import { ProxyBatchMode, ProxyFallbackMode, type BatchProxyDraft } from '@/features/admin/resources/proxy'
import { SortDirection, formatResourceDate } from '@/features/admin/resources/model'
import { ConfirmTone, useConfirmStore } from '@/stores/confirm'
import { useAppStore } from '@/stores/app'

enum ProxyStatus { ACTIVE = 'active', INACTIVE = 'inactive', EXPIRED = 'expired' }
const statusLabels: Record<ProxyStatus, string> = { [ProxyStatus.ACTIVE]: '启用', [ProxyStatus.INACTIVE]: '停用', [ProxyStatus.EXPIRED]: '已过期' }
const fallbackLabels: Record<ProxyFallbackMode, string> = { [ProxyFallbackMode.NONE]: '不回退', [ProxyFallbackMode.PROXY]: '备用代理', [ProxyFallbackMode.DIRECT]: '直连' }
const qualityLabels: Record<string, string> = { healthy: '健康', warn: '警告', challenge: '需验证', failed: '失败', pass: '通过', fail: '失败' }
const app = useAppStore(); const confirm = useConfirmStore(); const proxies = ref<Proxy[]>([]); const allProxies = ref<Proxy[]>([]); const total = ref(0); const page = ref(1); const pageSize = ref(20); const loading = ref(true); const error = ref('')
const filters = reactive({ search: '', protocol: '', status: '' }); const sort = reactive({ by: 'created_at', order: SortDirection.DESC }); const selected = ref<number[]>([])
const showEditor = ref(false); const editing = ref<Proxy | null>(null); const submitting = ref(false); const detail = ref<Proxy | null>(null); const batchMode = ref<ProxyBatchMode | null>(null); const batchSubmitting = ref(false); const batchTesting = ref(false); const batchQualityChecking = ref(false)
let controller: AbortController | null = null; let timer: number | null = null
const pages = computed(() => Math.max(1, Math.ceil(total.value / pageSize.value))); const selectedCount = computed(() => selected.value.length); const allSelected = computed(() => proxies.value.length > 0 && proxies.value.every(item => selected.value.includes(item.id)))
const active = computed(() => proxies.value.filter(item => item.status === 'active').length); const expiring = computed(() => proxies.value.filter(item => item.expires_at && new Date(item.expires_at).getTime() < Date.now() + item.expiry_warn_days * 86400000).length); const accounts = computed(() => proxies.value.reduce((sum, item) => sum + (item.account_count || 0), 0))
function requestFilters() { return { protocol: filters.protocol || undefined, status: (filters.status || undefined) as 'active' | 'inactive' | 'expired' | undefined, search: filters.search.trim() || undefined, sort_by: sort.by, sort_order: sort.order } }
async function loadReferences(): Promise<void> { try { allProxies.value = await proxiesAPI.getAllWithCount() } catch { allProxies.value = proxies.value } }
async function load(): Promise<void> { controller?.abort(); controller = new AbortController(); const current = controller; loading.value = true; error.value = ''; try { const response = await proxiesAPI.list(page.value, pageSize.value, requestFilters(), { signal: current.signal }); proxies.value = response.items; total.value = response.total; selected.value = selected.value.filter(id => response.items.some(item => item.id === id)); void loadReferences() } catch (caught) { if ((caught as { code?: string }).code !== 'ERR_CANCELED') error.value = (caught as { message?: string }).message || '代理加载失败' } finally { if (controller === current) loading.value = false } }
function searchLater(): void { if (timer) window.clearTimeout(timer); timer = window.setTimeout(() => { page.value = 1; void load() }, 280) }
function filter(): void { page.value = 1; void load() }
function setSort(by: string): void {
  if (sort.by === by) sort.order = sort.order === SortDirection.ASC ? SortDirection.DESC : SortDirection.ASC
  else { sort.by = by; sort.order = SortDirection.ASC }
  void load()
}
function toggleSelect(id: number): void { selected.value = selected.value.includes(id) ? selected.value.filter(item => item !== id) : [...selected.value, id] }
function toggleAll(): void { selected.value = allSelected.value ? [] : proxies.value.map(item => item.id) }
function create(): void { editing.value = null; showEditor.value = true }
async function edit(proxy: Proxy): Promise<void> { try { editing.value = await proxiesAPI.getById(proxy.id); showEditor.value = true } catch (caught) { app.showError((caught as { message?: string }).message || '代理详情加载失败') } }
async function save(payload: CreateProxyRequest | UpdateProxyRequest): Promise<void> { if (submitting.value) return; submitting.value = true; try { if (editing.value) await proxiesAPI.update(editing.value.id, payload as UpdateProxyRequest); else await proxiesAPI.create(payload as CreateProxyRequest); app.showSuccess(editing.value ? '代理已更新' : '代理已创建'); showEditor.value = false; await load() } catch (caught) { app.showError((caught as { message?: string }).message || '代理保存失败') } finally { submitting.value = false } }
async function toggleStatus(proxy: Proxy): Promise<void> { const next = proxy.status === 'active' ? 'inactive' : 'active'; if (next === 'inactive' && !await confirm.ask({ title: '停用代理', message: `停用 ${proxy.name} 可能影响 ${proxy.account_count || 0} 个关联账号。`, confirmText: '停用', tone: ConfirmTone.DANGER })) return; try { await proxiesAPI.toggleStatus(proxy.id, next); app.showSuccess(next === 'active' ? '代理已启用' : '代理已停用'); await load() } catch (caught) { app.showError((caught as { message?: string }).message || '状态更新失败') } }
async function remove(proxy: Proxy): Promise<void> { if (!await confirm.ask({ title: '删除代理', message: `确认删除 ${proxy.name}？关联账号存在时后端会按既有规则拒绝或处理。`, confirmText: '删除', tone: ConfirmTone.DANGER })) return; try { await proxiesAPI.deleteProxy(proxy.id); app.showSuccess('代理已删除'); await load() } catch (caught) { app.showError((caught as { message?: string }).message || '删除失败') } }
async function batchDelete(): Promise<void> { if (!selected.value.length || !await confirm.ask({ title: '批量删除代理', message: `确认删除选中的 ${selected.value.length} 个代理？无法删除的项目会返回具体原因。`, confirmText: '批量删除', tone: ConfirmTone.DANGER })) return; try { const result = await proxiesAPI.batchDelete(selected.value); app.showSuccess(`已删除 ${result.deleted_ids.length} 个，跳过 ${result.skipped.length} 个`); selected.value = []; await load() } catch (caught) { app.showError((caught as { message?: string }).message || '批量删除失败') } }
async function batchCreate(rows: BatchProxyDraft[]): Promise<void> { batchSubmitting.value = true; try { const result = await proxiesAPI.batchCreate(rows); app.showSuccess(`已创建 ${result.created} 个，跳过 ${result.skipped} 个`); batchMode.value = null; await load() } catch (caught) { app.showError((caught as { message?: string }).message || '批量创建失败') } finally { batchSubmitting.value = false } }
async function filteredProxyIds(): Promise<number[]> {
  if (selected.value.length) return [...selected.value]
  const ids: number[] = []; let current = 1; let pageCount = 1
  do { const response = await proxiesAPI.list(current, 100, requestFilters()); ids.push(...response.items.map(item => item.id)); pageCount = response.pages || 1; current += 1 } while (current <= pageCount)
  return ids
}
async function runConcurrent<T>(ids: number[], action: (id: number) => Promise<T>): Promise<Array<{ id: number; value?: T; error?: string }>> {
  const output: Array<{ id: number; value?: T; error?: string }> = []; let cursor = 0
  async function worker(): Promise<void> { while (cursor < ids.length) { const id = ids[cursor]; cursor += 1; try { output.push({ id, value: await action(id) }) } catch (caught) { output.push({ id, error: (caught as { message?: string }).message || '执行失败' }) } } }
  await Promise.all(Array.from({ length: Math.min(5, ids.length) }, () => worker()))
  return output
}
async function batchTest(): Promise<void> {
  if (batchTesting.value) return; batchTesting.value = true
  try { const ids = await filteredProxyIds(); if (!ids.length) { app.showError('当前筛选没有可测试的代理'); return } const results = await runConcurrent(ids, id => proxiesAPI.testProxy(id)); const success = results.filter(item => item.value?.success).length; const failed = results.length - success; app.showSuccess(`连通性测试完成：成功 ${success}，失败 ${failed}`); await load() } catch (caught) { app.showError((caught as { message?: string }).message || '批量连接测试失败') } finally { batchTesting.value = false }
}
async function batchQuality(): Promise<void> {
  if (batchQualityChecking.value) return; batchQualityChecking.value = true
  try { const ids = await filteredProxyIds(); if (!ids.length) { app.showError('当前筛选没有可检查的代理'); return } const results = await runConcurrent(ids, id => proxiesAPI.checkProxyQuality(id)); const completed = results.filter(item => item.value); const healthy = completed.filter(item => item.value!.grade === 'A' || item.value!.grade === 'B').length; const failed = results.length - healthy; app.showSuccess(`质量检查完成：健康 ${healthy}，需关注 ${failed}`); await load() } catch (caught) { app.showError((caught as { message?: string }).message || '批量质量检查失败') } finally { batchQualityChecking.value = false }
}
function proxyUrl(proxy: Proxy): string { const user = proxy.username ? encodeURIComponent(proxy.username) : ''; const password = proxy.password ? encodeURIComponent(proxy.password) : ''; const auth = user || password ? `${user}${password ? `:${password}` : ''}@` : ''; return `${proxy.protocol}://${auth}${proxy.host}:${proxy.port}` }
async function copyProxyUrl(proxy: Proxy): Promise<void> { try { await navigator.clipboard.writeText(proxyUrl(proxy)); app.showSuccess('代理 URL 已复制') } catch { app.showError('复制失败，请检查浏览器剪贴板权限') } }
function downloadJson(payload: AdminDataPayload): void { const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `sub2api-proxies-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url) }
async function exportData(): Promise<void> { if (!await confirm.ask({ title: '导出代理数据', message: selected.value.length ? `将导出选中的 ${selected.value.length} 个代理，文件可能包含凭据。` : '将按当前筛选条件导出代理，文件可能包含凭据。', confirmText: '下载 JSON' })) return; try { const payload = await proxiesAPI.exportData(selected.value.length ? { ids: selected.value } : { filters: requestFilters() }); downloadJson(payload); app.showSuccess('代理数据已下载') } catch (caught) { app.showError((caught as { message?: string }).message || '导出失败') } }
async function importData(payload: AdminDataPayload): Promise<void> { batchSubmitting.value = true; try { const result = await proxiesAPI.importData({ data: payload }); app.showSuccess(`已创建 ${result.proxy_created} 个代理，复用 ${result.proxy_reused} 个，失败 ${result.proxy_failed} 个`); batchMode.value = null; await load() } catch (caught) { app.showError((caught as { message?: string }).message || '导入失败') } finally { batchSubmitting.value = false } }
onMounted(load); onBeforeUnmount(() => { controller?.abort(); if (timer) window.clearTimeout(timer) })
</script>

<template><ConsoleShell><main class="resource-page"><header class="resource-page__heading"><div><span class="resource-eyebrow">Network Pool</span><h1>代理管理</h1><p>完整管理出口凭据、到期与回退策略，并提供批量导入导出、连通性和多目标质量诊断。</p></div><button class="resource-button" @click="create">创建代理</button></header>
  <section class="resource-summary"><div><span>当前页 / 总数</span><strong>{{ proxies.length }} / {{ total }}</strong></div><div><span>当前页启用</span><strong>{{ active }}</strong></div><div><span>即将到期</span><strong>{{ expiring }}</strong></div><div><span>关联账号</span><strong>{{ accounts }}</strong></div></section>
  <section class="resource-toolbar"><div class="resource-toolbar__filters"><input v-model="filters.search" type="search" placeholder="搜索名称、主机或出口 IP" @input="searchLater" /><select v-model="filters.protocol" @change="filter"><option value="">全部协议</option><option value="http">HTTP</option><option value="https">HTTPS</option><option value="socks5">SOCKS5</option><option value="socks5h">SOCKS5H</option></select><select v-model="filters.status" @change="filter"><option value="">全部状态</option><option value="active">启用</option><option value="inactive">停用</option><option value="expired">已过期</option></select></div><div class="resource-toolbar__actions"><button class="resource-button resource-button--secondary" @click="load">刷新</button><button class="resource-button resource-button--secondary" :disabled="batchTesting" @click="batchTest">{{ batchTesting ? '测试中…' : `连接测试${selectedCount ? ` ${selectedCount}` : ''}` }}</button><button class="resource-button resource-button--secondary" :disabled="batchQualityChecking" @click="batchQuality">{{ batchQualityChecking ? '检查中…' : `质量检查${selectedCount ? ` ${selectedCount}` : ''}` }}</button><button class="resource-button resource-button--secondary" @click="batchMode = ProxyBatchMode.CREATE">批量创建</button><button class="resource-button resource-button--secondary" @click="batchMode = ProxyBatchMode.IMPORT">导入</button><button class="resource-button resource-button--secondary" @click="exportData">导出{{ selectedCount ? ` ${selectedCount}` : '' }}</button><button v-if="selectedCount" class="resource-button resource-button--danger" @click="batchDelete">批量删除 {{ selectedCount }}</button></div></section>
  <PageState :loading="loading" :error="error" :empty="!loading && !error && proxies.length === 0" empty-text="没有匹配的代理。" @retry="load"><div class="resource-table"><table><thead><tr><th class="resource-table__select"><input type="checkbox" :checked="allSelected" aria-label="选择当前页" @change="toggleAll" /></th><th @click="setSort('name')">代理 ↕</th><th>连接</th><th>出口</th><th>质量</th><th>账号</th><th>回退</th><th @click="setSort('expires_at')">到期 ↕</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="proxy in proxies" :key="proxy.id"><td><input type="checkbox" :checked="selected.includes(proxy.id)" :aria-label="`选择 ${proxy.name}`" @change="toggleSelect(proxy.id)" /></td><td><button class="resource-link resource-proxy-name" @click="detail = proxy">{{ proxy.name }}</button><small>#{{ proxy.id }} · {{ proxy.protocol.toUpperCase() }}</small></td><td>{{ proxy.host }}:{{ proxy.port }}<small>{{ proxy.username ? '需认证' : '无认证' }} · {{ proxy.latency_ms ?? '—' }}ms</small></td><td>{{ proxy.ip_address || '—' }}<small>{{ [proxy.city, proxy.region, proxy.country].filter(Boolean).join(' · ') || '尚未测试' }}</small></td><td><span :class="['resource-status', proxy.quality_status === 'healthy' ? 'resource-status--active' : proxy.quality_status ? 'resource-status--degraded' : '']">{{ proxy.quality_grade || qualityLabels[proxy.quality_status || ''] || '未检查' }}</span><small>{{ proxy.quality_score ?? '—' }} 分</small></td><td><button class="resource-link" @click="detail = proxy">{{ proxy.account_count || 0 }}</button></td><td>{{ fallbackLabels[proxy.fallback_mode as ProxyFallbackMode] || proxy.fallback_mode }}<small v-if="proxy.backup_proxy_id">备用 #{{ proxy.backup_proxy_id }}</small></td><td>{{ formatResourceDate(proxy.expires_at) }}<small>提前 {{ proxy.expiry_warn_days }} 天提醒</small></td><td><button :class="['resource-status', `resource-status--${proxy.status}`]" @click="toggleStatus(proxy)">{{ statusLabels[proxy.status as ProxyStatus] || proxy.status }}</button></td><td><div class="resource-inline-actions"><button class="resource-link" @click="detail = proxy">诊断</button><button class="resource-link" @click="copyProxyUrl(proxy)">复制 URL</button><button class="resource-link" @click="edit(proxy)">编辑</button><button class="resource-link resource-link--danger" @click="remove(proxy)">删除</button></div></td></tr></tbody></table></div></PageState>
  <footer class="resource-pagination"><span>共 {{ total }} 条 · 第 {{ page }} / {{ pages }} 页</span><div class="resource-pagination__actions"><select v-model.number="pageSize" @change="page = 1; load()"><option :value="20">20 / 页</option><option :value="50">50 / 页</option><option :value="100">100 / 页</option></select><button class="resource-button resource-button--secondary" :disabled="page <= 1" @click="page--; load()">上一页</button><button class="resource-button resource-button--secondary" :disabled="page >= pages" @click="page++; load()">下一页</button></div></footer>
  </main><ProxyEditorDialog :show="showEditor" :proxy="editing" :proxies="allProxies" :submitting="submitting" @close="showEditor = false" @submit="save" /><ProxyDetailDialog :show="Boolean(detail)" :proxy="detail" @close="detail = null" @changed="load" /><ProxyBatchDialog :show="batchMode !== null" :mode="batchMode || ProxyBatchMode.CREATE" :submitting="batchSubmitting" @close="batchMode = null" @create="batchCreate" @import="importData" /></ConsoleShell></template>
<style scoped>.resource-proxy-name { padding-left: 0; color: var(--text-primary); font-size: 13px; }</style>
