<script setup lang="ts">
import { ref, watch } from 'vue'; import * as proxiesAPI from '@shared-api/admin/proxies'; import type { AccountPlatform, AccountType, Proxy, ProxyAccountSummary, ProxyQualityCheckResult } from '@/types'; import SurfaceDialog from '@/components/base/SurfaceDialog.vue'; import { DialogWidth } from '@/components/base/dialog'; import { useAppStore } from '@/stores/app'
enum QualityItemStatus { PASS = 'pass', WARN = 'warn', CHALLENGE = 'challenge', FAIL = 'fail' }
const qualityLabels: Record<QualityItemStatus, string> = { [QualityItemStatus.PASS]: '通过', [QualityItemStatus.WARN]: '警告', [QualityItemStatus.CHALLENGE]: '需验证', [QualityItemStatus.FAIL]: '失败' }
const platformLabels: Record<AccountPlatform, string> = { openai: 'OpenAI / Codex', anthropic: 'Anthropic / Claude', gemini: 'Google Gemini', antigravity: 'Antigravity', grok: 'Grok', kimi: 'Kimi', zhipu: '智谱', deepseek: 'DeepSeek' }
const typeLabels: Record<AccountType, string> = { oauth: 'OAuth', 'setup-token': 'Setup Token', apikey: 'API Key', upstream: '上游账号', bedrock: 'Amazon Bedrock', service_account: 'Service Account' }
const props = defineProps<{ show: boolean; proxy: Proxy | null }>(); const emit = defineEmits<{ close: []; changed: [] }>(); const app = useAppStore(); const stats = ref<Awaited<ReturnType<typeof proxiesAPI.getStats>> | null>(null); const accounts = ref<ProxyAccountSummary[]>([]); const quality = ref<ProxyQualityCheckResult | null>(null); const loading = ref(false); const testing = ref(false); const checking = ref(false); const testMessage = ref('')
async function load(): Promise<void> { if (!props.proxy) return; loading.value = true; try { const [s, a] = await Promise.all([proxiesAPI.getStats(props.proxy.id), proxiesAPI.getProxyAccounts(props.proxy.id)]); stats.value = s; accounts.value = a } catch (caught) { app.showError((caught as { message?: string }).message || '代理详情加载失败') } finally { loading.value = false } }
async function test(): Promise<void> { if (!props.proxy) return; testing.value = true; try { const result = await proxiesAPI.testProxy(props.proxy.id); testMessage.value = `${result.success ? '连接成功' : '连接失败'} · ${result.latency_ms ?? '—'} ms · ${result.ip_address || '未知 IP'} · ${result.message}`; result.success ? app.showSuccess('代理连接测试成功') : app.showError(result.message); emit('changed') } catch (caught) { app.showError((caught as { message?: string }).message || '连接测试失败') } finally { testing.value = false } }
async function check(): Promise<void> { if (!props.proxy) return; checking.value = true; try { quality.value = await proxiesAPI.checkProxyQuality(props.proxy.id); app.showSuccess('质量检查完成'); emit('changed') } catch (caught) { app.showError((caught as { message?: string }).message || '质量检查失败') } finally { checking.value = false } }
watch(() => props.show, (show) => { if (show) { quality.value = null; testMessage.value = ''; void load() } })
</script>
<template><SurfaceDialog :show="show" :title="`代理诊断 · ${proxy?.name || ''}`" description="连接测试读取出口信息；质量检查会探测多个常用 AI 目标。" :width="DialogWidth.WIDE" @close="emit('close')"><div class="resource-form-stack"><div class="resource-inline-actions"><button class="resource-button" :disabled="testing" @click="test">{{ testing ? '连接测试中…' : '连接测试' }}</button><button class="resource-button resource-button--secondary" :disabled="checking" @click="check">{{ checking ? '质量检查中…' : '质量检查' }}</button></div><p v-if="testMessage" class="notice">{{ testMessage }}</p><div class="resource-summary"><div><span>账号</span><strong>{{ stats?.total_accounts ?? '—' }}</strong></div><div><span>活跃账号</span><strong>{{ stats?.active_accounts ?? '—' }}</strong></div><div><span>成功率</span><strong>{{ stats ? `${stats.success_rate.toFixed(1)}%` : '—' }}</strong></div><div><span>平均延迟</span><strong>{{ stats ? `${stats.average_latency}ms` : '—' }}</strong></div></div><section v-if="quality" class="quality-card"><div><strong>{{ quality.grade }}</strong><span>{{ quality.score }} 分</span></div><p>{{ quality.summary }}</p><div class="quality-grid"><article v-for="item in quality.items" :key="item.target"><span :class="['resource-status', `resource-status--${item.status === 'pass' ? 'active' : item.status === 'fail' ? 'failed' : 'degraded'}`]">{{ qualityLabels[item.status as QualityItemStatus] || item.status }}</span><strong>{{ item.target }}</strong><small>{{ item.http_status || '—' }} · {{ item.latency_ms || '—' }}ms · {{ item.message || '—' }}</small></article></div></section><div class="resource-table"><table><thead><tr><th>关联账号</th><th>平台</th><th>类型</th><th>备注</th></tr></thead><tbody><tr v-if="loading"><td colspan="4">加载中…</td></tr><tr v-else-if="accounts.length === 0"><td colspan="4">暂无关联账号</td></tr><tr v-for="account in accounts" :key="account.id"><td>{{ account.name }} <small>#{{ account.id }}</small></td><td>{{ platformLabels[account.platform] }}</td><td>{{ typeLabels[account.type] }}</td><td>{{ account.notes || '—' }}</td></tr></tbody></table></div></div></SurfaceDialog></template>
<style scoped>.quality-card { padding: 16px; display: grid; gap: 12px; background: var(--surface-canvas); border-radius: 12px; }.quality-card > div:first-child { display: flex; align-items: baseline; justify-content: space-between; }.quality-card > div:first-child strong { font-size: 32px; }.quality-card p { margin: 0; color: var(--text-secondary); }.quality-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 7px; }.quality-grid article { padding: 10px; display: grid; grid-template-columns: auto 1fr; gap: 4px 8px; background: var(--surface-raised); border-radius: 9px; }.quality-grid small { grid-column: 2; color: var(--text-secondary); } @media(max-width:650px){.quality-grid{grid-template-columns:1fr}}</style>
