<script setup lang="ts">
import { ref, watch } from 'vue'
import * as monitorAPI from '@shared-api/admin/channelMonitor'
import type { ChannelMonitor, CheckResult, HistoryItem } from '@shared-api/admin/channelMonitor'
import SurfaceDialog from '@/components/base/SurfaceDialog.vue'
import { DialogWidth } from '@/components/base/dialog'
import { formatResourceDate } from '@/features/admin/resources/model'
import { useAppStore } from '@/stores/app'

const props = defineProps<{ show: boolean; monitor: ChannelMonitor | null }>(); const emit = defineEmits<{ close: [] }>(); const app = useAppStore()
const history = ref<HistoryItem[]>([]); const results = ref<CheckResult[]>([]); const loading = ref(false); const running = ref(false); const model = ref(''); const limit = ref(50)
async function load(): Promise<void> { if (!props.monitor) return; loading.value = true; try { history.value = (await monitorAPI.listHistory(props.monitor.id, { model: model.value || undefined, limit: limit.value })).items } catch (caught) { app.showError((caught as { message?: string }).message || '历史加载失败') } finally { loading.value = false } }
async function run(): Promise<void> { if (!props.monitor || running.value) return; running.value = true; try { results.value = (await monitorAPI.runNow(props.monitor.id)).results; app.showSuccess('即时检查已完成'); await load() } catch (caught) { app.showError((caught as { message?: string }).message || '即时检查失败') } finally { running.value = false } }
watch(() => props.show, (show) => { if (show) { results.value = []; model.value = ''; void load() } })
</script>
<template><SurfaceDialog :show="show" :title="`检查与历史 · ${monitor?.name || ''}`" description="即时检查会请求主模型与额外模型，并写入同一历史记录。" :width="DialogWidth.WIDE" @close="emit('close')"><div class="resource-form-stack"><div class="resource-toolbar"><div class="resource-toolbar__filters"><select v-model="model" @change="load"><option value="">全部模型</option><option v-for="item in [monitor?.primary_model, ...(monitor?.extra_models || [])].filter(Boolean)" :key="item" :value="item">{{ item }}</option></select><select v-model.number="limit" @change="load"><option :value="20">20 条</option><option :value="50">50 条</option><option :value="100">100 条</option></select></div><button class="resource-button" :disabled="running" @click="run">{{ running ? '检查中…' : '立即检查' }}</button></div><section v-if="results.length" class="run-results"><article v-for="result in results" :key="result.model"><span :class="['resource-status', `resource-status--${result.status}`]">{{ result.status }}</span><strong>{{ result.model }}</strong><small>{{ result.latency_ms ?? '—' }} ms · {{ result.message }}</small></article></section><div class="resource-table"><table><thead><tr><th>时间</th><th>模型</th><th>状态</th><th>接口 / Ping</th><th>消息</th></tr></thead><tbody><tr v-if="loading"><td colspan="5">加载中…</td></tr><tr v-else-if="history.length === 0"><td colspan="5">暂无检查历史</td></tr><tr v-for="item in history" :key="item.id"><td>{{ formatResourceDate(item.checked_at) }}</td><td>{{ item.model }}</td><td><span :class="['resource-status', `resource-status--${item.status}`]">{{ item.status }}</span></td><td>{{ item.latency_ms ?? '—' }} / {{ item.ping_latency_ms ?? '—' }} ms</td><td>{{ item.message || '—' }}</td></tr></tbody></table></div></div></SurfaceDialog></template>
<style scoped>.run-results { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; }.run-results article { padding: 12px; display: grid; grid-template-columns: auto 1fr; gap: 5px 9px; background: var(--surface-canvas); border-radius: 10px; }.run-results small { grid-column: 2; color: var(--text-secondary); } @media(max-width:650px){.run-results{grid-template-columns:1fr}}</style>
