<script setup lang="ts">
import { computed, ref, watch } from 'vue'; import * as templateAPI from '@shared-api/admin/channelMonitorTemplate'; import type { AssociatedMonitorBrief, ChannelMonitorTemplate } from '@shared-api/admin/channelMonitorTemplate'; import SurfaceDialog from '@/components/base/SurfaceDialog.vue'; import { DialogWidth } from '@/components/base/dialog'; import { useAppStore } from '@/stores/app'
const props = defineProps<{ show: boolean; template: ChannelMonitorTemplate | null }>(); const emit = defineEmits<{ close: []; applied: [] }>(); const app = useAppStore(); const rows = ref<AssociatedMonitorBrief[]>([]); const selected = ref<number[]>([]); const loading = ref(false); const applying = ref(false); const allSelected = computed(() => rows.value.length > 0 && rows.value.every(item => selected.value.includes(item.id)))
async function load(): Promise<void> { if (!props.template) return; loading.value = true; try { rows.value = (await templateAPI.listAssociatedMonitors(props.template.id)).items; selected.value = rows.value.map(item => item.id) } catch (caught) { app.showError((caught as { message?: string }).message || '关联监控加载失败') } finally { loading.value = false } }
function toggle(id: number): void { selected.value = selected.value.includes(id) ? selected.value.filter(item => item !== id) : [...selected.value, id] }
function toggleAll(): void { selected.value = allSelected.value ? [] : rows.value.map(item => item.id) }
async function apply(): Promise<void> { if (!props.template || !selected.value.length || applying.value) return; applying.value = true; try { const result = await templateAPI.apply(props.template.id, selected.value); app.showSuccess(`已更新 ${result.affected} 个监控`); emit('applied'); emit('close') } catch (caught) { app.showError((caught as { message?: string }).message || '模板应用失败') } finally { applying.value = false } }
watch(() => props.show, (show) => { if (show) void load() })
</script>
<template><SurfaceDialog :show="show" :title="`应用模板 · ${template?.name || ''}`" description="只覆盖选中关联监控的 headers 与 body 快照，不修改密钥、模型和调度周期。" :width="DialogWidth.STANDARD" @close="emit('close')"><div class="resource-form-stack"><label class="resource-check"><input type="checkbox" :checked="allSelected" @change="toggleAll" /><span>全选关联监控</span></label><div v-if="loading">加载中…</div><div v-else-if="rows.length === 0" class="resource-empty-inline">当前没有关联监控。</div><div v-else class="apply-list"><label v-for="monitor in rows" :key="monitor.id"><input type="checkbox" :checked="selected.includes(monitor.id)" @change="toggle(monitor.id)" /><span><strong>{{ monitor.name }}</strong><small>{{ monitor.provider }} · {{ monitor.api_mode }} · {{ monitor.enabled ? '启用' : '停用' }}</small></span></label></div></div><template #footer><button class="button button--secondary" @click="emit('close')">取消</button><button class="button button--primary" :disabled="!selected.length || applying" @click="apply">{{ applying ? '应用中…' : `应用到 ${selected.length} 个监控` }}</button></template></SurfaceDialog></template>
<style scoped>.apply-list { display: grid; gap: 7px; }.apply-list label { padding: 11px; display: flex; gap: 9px; background: var(--surface-canvas); border-radius: 9px; }.apply-list span { display: grid; gap: 4px; }.apply-list small { color: var(--text-secondary); }</style>
