<script setup lang="ts">
import { reactive, watch } from 'vue'
import type { ChannelMonitorTemplate, CreateParams, UpdateParams } from '@shared-api/admin/channelMonitorTemplate'
import SurfaceDialog from '@/components/base/SurfaceDialog.vue'; import { DialogWidth } from '@/components/base/dialog'; import { parseJsonValue } from '@/features/admin/resources/model'; import { useAppStore } from '@/stores/app'
const props = defineProps<{ show: boolean; template: ChannelMonitorTemplate | null; submitting?: boolean }>(); const emit = defineEmits<{ close: []; submit: [payload: CreateParams | UpdateParams] }>(); const app = useAppStore()
const form = reactive({ name: '', provider: 'openai', api_mode: 'chat_completions', description: '', extra_headers_json: '{}', body_override_mode: 'off', body_override_json: '{}' })
function reset(): void { const value = props.template; Object.assign(form, value ? { name: value.name, provider: value.provider, api_mode: value.api_mode, description: value.description, extra_headers_json: JSON.stringify(value.extra_headers || {}, null, 2), body_override_mode: value.body_override_mode, body_override_json: JSON.stringify(value.body_override || {}, null, 2) } : { name: '', provider: 'openai', api_mode: 'chat_completions', description: '', extra_headers_json: '{}', body_override_mode: 'off', body_override_json: '{}' }) }
function submit(): void { if (!form.name.trim()) { app.showError('模板名称不能为空'); return } try { emit('submit', { name: form.name.trim(), provider: form.provider as CreateParams['provider'], api_mode: form.api_mode as CreateParams['api_mode'], description: form.description.trim(), extra_headers: parseJsonValue(form.extra_headers_json, '额外请求头', {}), body_override_mode: form.body_override_mode as CreateParams['body_override_mode'], body_override: form.body_override_mode === 'off' ? null : parseJsonValue(form.body_override_json, '请求体覆盖', {}) }) } catch (caught) { app.showError((caught as Error).message) } }
watch(() => props.show, (show) => { if (show) reset() })
</script>
<template><SurfaceDialog :show="show" :title="template ? '编辑请求模板' : '创建请求模板'" description="模板应用时复制请求快照；后续修改不会自动覆盖关联监控。" :width="DialogWidth.WIDE" @close="emit('close')"><form id="template-editor-form" class="resource-form-stack" @submit.prevent="submit"><div class="resource-form-grid resource-form-grid--3"><label class="resource-field--wide">名称 *<input v-model="form.name" /></label><label>提供商<select v-model="form.provider" :disabled="Boolean(template)"><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Gemini</option><option value="grok">Grok</option></select></label><label>API 模式<select v-model="form.api_mode"><option value="chat_completions">Chat Completions</option><option value="responses">Responses</option></select></label><label class="resource-field--wide">说明<textarea v-model="form.description" rows="3" /></label></div><label>额外请求头（JSON）<textarea v-model="form.extra_headers_json" rows="6" class="resource-code" /></label><label>请求体覆盖方式<select v-model="form.body_override_mode"><option value="off">关闭</option><option value="merge">合并</option><option value="replace">完全替换</option></select></label><label v-if="form.body_override_mode !== 'off'">请求体覆盖（JSON）<textarea v-model="form.body_override_json" rows="7" class="resource-code" /></label></form><template #footer><button class="button button--secondary" @click="emit('close')">取消</button><button type="submit" form="template-editor-form" class="button button--primary" :disabled="submitting">{{ submitting ? '保存中…' : '保存模板' }}</button></template></SurfaceDialog></template>
