<script setup lang="ts">
import { reactive, ref, watch } from 'vue'; import type { AdminGroup, Proxy } from '@/types'; import SurfaceDialog from '@/components/base/SurfaceDialog.vue'; import { DialogWidth } from '@/components/base/dialog'; import { parseJsonValue } from '@/features/admin/resources/model'; import { useAppStore } from '@/stores/app'
enum BulkTab { FIELDS = 'fields', ADVANCED = 'advanced', CREDENTIAL = 'credential' }
const props = defineProps<{ show: boolean; count: number; groups: AdminGroup[]; proxies: Proxy[]; submitting?: boolean }>(); const emit = defineEmits<{ close: []; update: [payload: Record<string, unknown>]; credential: [field: string, value: unknown] }>(); const app = useAppStore(); const tab = ref(BulkTab.FIELDS); const enabled = reactive({ status: false, schedulable: false, proxy: false, concurrency: false, loadFactor: false, priority: false, rate: false, groups: false, probe: false, extra: false }); const form = reactive({ status: 'active', schedulable: true, proxy_id: '' as string | number, concurrency: 1, load_factor: 1, priority: 0, rate_multiplier: 1, group_ids: [] as number[], probe: false, extra_json: '{}', credential_field: '', credential_value_json: 'null' })
function toggleGroup(id: number): void { form.group_ids = form.group_ids.includes(id) ? form.group_ids.filter(item => item !== id) : [...form.group_ids, id] }
function submit(): void { try { if (tab.value === BulkTab.CREDENTIAL) { if (!form.credential_field.trim()) throw new Error('凭据字段名不能为空'); emit('credential', form.credential_field.trim(), parseJsonValue(form.credential_value_json, '凭据字段值', null)); return } const payload: Record<string, unknown> = {}; if (enabled.status) payload.status = form.status; if (enabled.schedulable) payload.schedulable = form.schedulable; if (enabled.proxy) payload.proxy_id = form.proxy_id === '' ? 0 : Number(form.proxy_id); if (enabled.concurrency) payload.concurrency = form.concurrency; if (enabled.loadFactor) payload.load_factor = form.load_factor; if (enabled.priority) payload.priority = form.priority; if (enabled.rate) payload.rate_multiplier = form.rate_multiplier; if (enabled.groups) payload.group_ids = [...form.group_ids]; if (enabled.probe) payload.upstream_billing_probe_enabled = form.probe; if (enabled.extra) payload.extra = parseJsonValue(form.extra_json, 'Extra 合并补丁', {}); if (!Object.keys(payload).length) throw new Error('至少启用一个要修改的字段'); emit('update', payload) } catch (caught) { app.showError((caught as Error).message) } }
watch(() => props.show, (show) => { if (show) { Object.keys(enabled).forEach(key => (enabled as unknown as Record<string, boolean>)[key] = false); tab.value = BulkTab.FIELDS } })
</script>
<template><SurfaceDialog :show="show" :title="`批量编辑 ${count} 个账号`" description="只有勾选启用的字段会提交；Extra 与 Credentials 继续使用后端既有 JSONB 合并语义。" :width="DialogWidth.WIDE" @close="emit('close')"><form id="account-bulk-form" class="resource-form-stack" @submit.prevent="submit"><div class="resource-tabs"><button type="button" :aria-selected="tab === BulkTab.FIELDS" @click="tab = BulkTab.FIELDS">基础调度</button><button type="button" :aria-selected="tab === BulkTab.ADVANCED" @click="tab = BulkTab.ADVANCED">分组与 Extra</button><button type="button" :aria-selected="tab === BulkTab.CREDENTIAL" @click="tab = BulkTab.CREDENTIAL">单一凭据字段</button></div>
  <div v-if="tab === BulkTab.FIELDS" class="bulk-grid"><fieldset><label class="resource-check"><input v-model="enabled.status" type="checkbox" /><span>修改状态</span></label><select v-model="form.status" :disabled="!enabled.status"><option value="active">启用</option><option value="inactive">停用</option><option value="error">异常</option></select></fieldset><fieldset><label class="resource-check"><input v-model="enabled.schedulable" type="checkbox" /><span>修改调度</span></label><select v-model="form.schedulable" :disabled="!enabled.schedulable"><option :value="true">参与调度</option><option :value="false">暂停调度</option></select></fieldset><fieldset><label class="resource-check"><input v-model="enabled.proxy" type="checkbox" /><span>修改代理</span></label><select v-model="form.proxy_id" :disabled="!enabled.proxy"><option value="">清除代理</option><option v-for="proxy in proxies" :key="proxy.id" :value="proxy.id">{{ proxy.name }}</option></select></fieldset><fieldset><label class="resource-check"><input v-model="enabled.concurrency" type="checkbox" /><span>修改并发</span></label><input v-model.number="form.concurrency" :disabled="!enabled.concurrency" type="number" min="1" /></fieldset><fieldset><label class="resource-check"><input v-model="enabled.loadFactor" type="checkbox" /><span>修改负载系数</span></label><input v-model.number="form.load_factor" :disabled="!enabled.loadFactor" type="number" min="0" step="any" /></fieldset><fieldset><label class="resource-check"><input v-model="enabled.priority" type="checkbox" /><span>修改优先级</span></label><input v-model.number="form.priority" :disabled="!enabled.priority" type="number" /></fieldset><fieldset><label class="resource-check"><input v-model="enabled.rate" type="checkbox" /><span>修改计费倍率</span></label><input v-model.number="form.rate_multiplier" :disabled="!enabled.rate" type="number" min="0" step="any" /></fieldset><fieldset><label class="resource-check"><input v-model="enabled.probe" type="checkbox" /><span>修改上游计费探测</span></label><select v-model="form.probe" :disabled="!enabled.probe"><option :value="true">启用</option><option :value="false">关闭</option></select></fieldset></div>
  <div v-else-if="tab === BulkTab.ADVANCED" class="resource-form-stack"><fieldset class="resource-form-section"><label class="resource-check"><input v-model="enabled.groups" type="checkbox" /><span>替换绑定分组</span></label><div class="bulk-group-grid"><label v-for="group in groups" :key="group.id" class="resource-check"><input type="checkbox" :disabled="!enabled.groups" :checked="form.group_ids.includes(group.id)" @change="toggleGroup(group.id)" /><span>{{ group.name }} · {{ group.platform }}</span></label></div></fieldset><fieldset class="resource-form-section"><label class="resource-check"><input v-model="enabled.extra" type="checkbox" /><span>合并 Extra 补丁</span></label><textarea v-model="form.extra_json" :disabled="!enabled.extra" rows="10" class="resource-code" /></fieldset></div>
  <div v-else class="resource-form-grid"><label>Credentials 字段名<input v-model="form.credential_field" placeholder="model_mapping" /></label><label>字段值（JSON）<textarea v-model="form.credential_value_json" rows="8" class="resource-code" /></label></div>
  </form><template #footer><button class="button button--secondary" @click="emit('close')">取消</button><button type="submit" form="account-bulk-form" class="button button--primary" :disabled="submitting">{{ submitting ? '处理中…' : '应用批量修改' }}</button></template></SurfaceDialog></template>
<style scoped>.bulk-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 9px; }.bulk-grid fieldset { margin: 0; padding: 11px; display: grid; gap: 8px; border: 1px solid var(--border-subtle); border-radius: 10px; }.bulk-grid select,.bulk-grid input { min-height: 40px; padding: 7px; color: var(--text-primary); background: var(--surface-raised); border: 1px solid var(--border-subtle); border-radius: 8px; }.bulk-group-grid { display: grid; grid-template-columns: repeat(2,1fr); gap: 7px; } @media(max-width:650px){.bulk-grid,.bulk-group-grid{grid-template-columns:1fr}}</style>
