<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import * as accountsAPI from '@shared-api/admin/accounts'
import * as cnProvidersAPI from '@shared-api/admin/cnProviders'
import * as grokAPI from '@shared-api/admin/grok'
import * as scheduledTestsAPI from '@shared-api/admin/scheduledTests'
import type { Account, CreateScheduledTestPlanRequest, ScheduledTestPlan, ScheduledTestResult } from '@/types'
import SurfaceDialog from '@/components/base/SurfaceDialog.vue'
import { DialogWidth } from '@/components/base/dialog'
import { ConfirmTone, useConfirmStore } from '@/stores/confirm'
import { formatResourceDate } from '@/features/admin/resources/model'
import { useAppStore } from '@/stores/app'

enum WorkspaceTab { ACTIONS = 'actions', USAGE = 'usage', QUOTA = 'quota', MODELS = 'models', SCHEDULE = 'schedule', BILLING = 'billing', OLLAMA = 'ollama' }
const workspaceTabLabels: Record<WorkspaceTab, string> = { [WorkspaceTab.ACTIONS]: '运行操作', [WorkspaceTab.USAGE]: '用量统计', [WorkspaceTab.QUOTA]: '平台配额', [WorkspaceTab.MODELS]: '可用模型', [WorkspaceTab.SCHEDULE]: '定时测试', [WorkspaceTab.BILLING]: '上游计费', [WorkspaceTab.OLLAMA]: 'Ollama Cloud' }
const props = defineProps<{ show: boolean; account: Account | null }>(); const emit = defineEmits<{ close: []; changed: [] }>(); const app = useAppStore(); const confirm = useConfirmStore(); const tab = ref(WorkspaceTab.ACTIONS); const running = ref(''); const outputTitle = ref(''); const output = ref<unknown>(null); const days = ref(30); const models = ref<Array<{ id: string; display_name?: string }>>([]); const plans = ref<ScheduledTestPlan[]>([]); const results = ref<Record<number, ScheduledTestResult[]>>({}); const scheduleForm = reactive({ id: null as number | null, model_id: '', cron_expression: '0 */6 * * *', enabled: true, max_results: 30, auto_recover: false }); const probeEnabled = ref(false); const globalProbe = reactive({ enabled: false, interval_minutes: 60 }); const ollamaSession = ref(''); const ollamaAuto = ref(false); const ollamaSettings = reactive({ enabled: false, interval_minutes: 60, debounce_minutes: 10 }); const shadow = reactive({ name: '', priority: 0, concurrency: 1 })
const outputText = computed(() => output.value == null ? '' : JSON.stringify(output.value, null, 2))
async function run<T>(name: string, action: () => Promise<T>, success?: string): Promise<T | null> { if (running.value) return null; running.value = name; try { const result = await action(); outputTitle.value = name; output.value = result; if (success) app.showSuccess(success); return result } catch (caught) { app.showError((caught as { message?: string }).message || `${name}失败`); return null } finally { running.value = '' } }
async function mutate<T>(name: string, action: () => Promise<T>, success: string): Promise<void> { const result = await run(name, action, success); if (result != null) emit('changed') }
async function loadModels(): Promise<void> { const value = await run('可用模型', () => accountsAPI.getAvailableModels(props.account!.id)); if (value) models.value = value }
async function loadPlans(): Promise<void> { if (!props.account) return; const value = await run('定时测试计划', () => scheduledTestsAPI.listByAccount(props.account!.id)); if (value) plans.value = value }
function resetSchedule(): void { Object.assign(scheduleForm, { id: null, model_id: '', cron_expression: '0 */6 * * *', enabled: true, max_results: 30, auto_recover: false }) }
function editPlan(plan: ScheduledTestPlan): void { Object.assign(scheduleForm, { id: plan.id, model_id: plan.model_id, cron_expression: plan.cron_expression, enabled: plan.enabled, max_results: plan.max_results, auto_recover: plan.auto_recover }) }
async function savePlan(): Promise<void> { if (!props.account || !scheduleForm.model_id || !scheduleForm.cron_expression) { app.showError('模型与 Cron 表达式不能为空'); return } const payload: CreateScheduledTestPlanRequest = { account_id: props.account.id, model_id: scheduleForm.model_id, cron_expression: scheduleForm.cron_expression, enabled: scheduleForm.enabled, max_results: scheduleForm.max_results, auto_recover: scheduleForm.auto_recover }; if (scheduleForm.id) await mutate('更新定时测试', () => scheduledTestsAPI.update(scheduleForm.id!, payload), '计划已更新'); else await mutate('创建定时测试', () => scheduledTestsAPI.create(payload), '计划已创建'); resetSchedule(); await loadPlans() }
async function deletePlan(plan: ScheduledTestPlan): Promise<void> { if (!await confirm.ask({ title: '删除定时测试', message: `确认删除 ${plan.model_id} 的定时测试计划？`, confirmText: '删除', tone: ConfirmTone.DANGER })) return; await mutate('删除定时测试', () => scheduledTestsAPI.deletePlan(plan.id), '计划已删除'); await loadPlans() }
async function loadResults(plan: ScheduledTestPlan): Promise<void> { const value = await run('定时测试结果', () => scheduledTestsAPI.listResults(plan.id, 50)); if (value) results.value[plan.id] = value }
async function resetOpenAI(): Promise<void> { if (!props.account || !await confirm.ask({ title: '消耗重置额度？', message: '该操作会消耗一个不可退还的 OpenAI/Codex 重置额度，并立即刷新上游配额。', confirmText: '确认重置', tone: ConfirmTone.DANGER })) return; await mutate('重置 OpenAI 配额', () => accountsAPI.resetOpenAIQuota(props.account!.id), 'OpenAI 配额已重置') }
async function resetGrok(): Promise<void> { if (!props.account || !await confirm.ask({ title: '重置 Grok 配额', message: '请求上游执行配额重置；是否支持由返回结果决定。', confirmText: '请求重置' })) return; await mutate('重置 Grok 配额', () => grokAPI.resetQuota(props.account!.id), 'Grok 重置请求已完成') }
async function createShadow(): Promise<void> { if (!props.account || !await confirm.ask({ title: '创建 Spark 影子账号', message: `将基于 ${props.account.name} 创建 quota_dimension 影子账号。`, confirmText: '创建' })) return; await mutate('创建 Spark 影子账号', () => accountsAPI.createSparkShadow(props.account!.id, { name: shadow.name || undefined, priority: shadow.priority, concurrency: shadow.concurrency }), '影子账号已创建') }
async function loadBillingSettings(): Promise<void> { const result = await run('上游计费全局设置', () => accountsAPI.getUpstreamBillingProbeSettings()); if (result) Object.assign(globalProbe, result) }
async function saveBillingSettings(): Promise<void> { await mutate('保存上游计费设置', () => accountsAPI.updateUpstreamBillingProbeSettings({ ...globalProbe }), '全局探测设置已保存') }
async function toggleProbe(): Promise<void> { if (!props.account) return; await mutate('更新账号探测开关', () => accountsAPI.setUpstreamBillingProbeEnabled(props.account!.id, probeEnabled.value), '账号探测开关已更新') }
async function loadOllama(): Promise<void> { if (!props.account) return; const [state, settings] = await Promise.all([run('Ollama Cloud 用量', () => accountsAPI.getOllamaCloudUsage(props.account!.id)), accountsAPI.getOllamaCloudUsageSettings().catch(() => null)]); if (state) ollamaAuto.value = state.auto_refresh_enabled; if (settings) Object.assign(ollamaSettings, settings) }
async function saveOllamaSettings(): Promise<void> { await mutate('保存 Ollama 全局设置', () => accountsAPI.updateOllamaCloudUsageSettings({ ...ollamaSettings }), 'Ollama 刷新设置已保存') }
async function deleteOllamaSession(): Promise<void> { if (!props.account || !await confirm.ask({ title: '删除 Ollama Session', message: '删除后将无法继续刷新该账号的云端用量，直到重新录入。', confirmText: '删除', tone: ConfirmTone.DANGER })) return; await mutate('删除 Ollama Session', () => accountsAPI.deleteOllamaCloudUsageSession(props.account!.id), 'Session 已删除') }
async function copyOutput(): Promise<void> { await globalThis.navigator.clipboard.writeText(outputText.value); app.showSuccess('结果已复制') }
watch(() => props.show, (show) => { if (!show || !props.account) return; tab.value = WorkspaceTab.ACTIONS; output.value = null; outputTitle.value = ''; probeEnabled.value = props.account.extra?.upstream_billing_probe_enabled === true; resetSchedule() })
watch(tab, (next) => { if (!props.show || !props.account) return; output.value = null; outputTitle.value = ''; if (next === WorkspaceTab.MODELS && !models.value.length) void loadModels(); if (next === WorkspaceTab.SCHEDULE) void Promise.all([loadModels(), loadPlans()]); if (next === WorkspaceTab.BILLING) void loadBillingSettings(); if (next === WorkspaceTab.OLLAMA) void loadOllama() })
</script>

<template><SurfaceDialog :show="show" :title="`账号工作台 · ${account?.name || ''}`" description="专项动作保持各自确认、结果与恢复语义，不退化为统一状态切换。" :width="DialogWidth.WIDE" @close="emit('close')"><div class="resource-form-stack"><div class="resource-tabs"><button v-for="item in WorkspaceTab" :key="item" :aria-selected="tab === item" @click="tab = item">{{ workspaceTabLabels[item] }}</button></div>
  <section v-if="tab === WorkspaceTab.ACTIONS" class="action-grid"><button @click="run('连接测试', () => accountsAPI.testAccount(account!.id))">连接测试</button><button @click="mutate('刷新凭据', () => accountsAPI.refreshCredentials(account!.id), '凭据已刷新')">刷新凭据</button><button @click="mutate('清除错误', () => accountsAPI.clearError(account!.id), '错误已清除')">清除错误</button><button @click="mutate('清除限流', () => accountsAPI.clearRateLimit(account!.id), '限流状态已清除')">清除限流</button><button @click="mutate('恢复运行态', () => accountsAPI.recoverState(account!.id), '运行态已恢复')">恢复全部运行态</button><button @click="mutate('重置本地配额', () => accountsAPI.resetAccountQuota(account!.id), '本地配额已重置')">重置本地配额</button><button @click="run('临时不可调度状态', () => accountsAPI.getTempUnschedulableStatus(account!.id))">查看临时不可调度</button><button @click="mutate('清除临时不可调度', () => accountsAPI.resetTempUnschedulable(account!.id), '临时状态已清除')">清除临时不可调度</button><button @click="mutate('切换调度', () => accountsAPI.setSchedulable(account!.id, !account!.schedulable), '调度状态已更新')">{{ account?.schedulable ? '暂停调度' : '恢复调度' }}</button><button v-if="account?.proxy_fallback_origin_id" @click="mutate('恢复原代理', () => accountsAPI.revertProxyFallback(account!.id), '已恢复原代理')">恢复原代理</button><button v-if="account?.platform === 'antigravity'" @click="mutate('设置隐私', () => accountsAPI.setPrivacy(account!.id), '隐私设置已完成')">设置隐私</button><button v-if="account?.platform === 'openai'" @click="createShadow">创建 Spark 影子账号</button></section>
  <section v-else-if="tab === WorkspaceTab.USAGE" class="resource-form-stack"><div class="resource-toolbar"><div class="resource-toolbar__filters"><label>统计天数 <input v-model.number="days" type="number" min="1" max="365" /></label></div></div><div class="action-grid"><button @click="run('账号统计', () => accountsAPI.getStats(account!.id, days))">加载统计</button><button @click="run('今日统计', () => accountsAPI.getTodayStats(account!.id))">今日统计</button><button @click="run('被动用量快照', () => accountsAPI.getUsage(account!.id, 'passive'))">被动快照</button><button @click="run('主动刷新用量', () => accountsAPI.getUsage(account!.id, 'active', true))">主动刷新</button></div></section>
  <section v-else-if="tab === WorkspaceTab.QUOTA" class="resource-form-stack"><div class="action-grid"><button v-if="account?.platform === 'openai'" @click="run('刷新 OpenAI 配额', () => accountsAPI.refreshOpenAIQuota(account!.id))">刷新 OpenAI 配额</button><button v-if="account?.platform === 'openai'" class="danger" @click="resetOpenAI">消耗额度重置</button><button v-if="account?.platform === 'grok'" @click="run('查询 Grok 配额', () => grokAPI.queryQuota(account!.id))">查询 Grok 配额</button><button v-if="account?.platform === 'grok'" @click="resetGrok">请求 Grok 重置</button><button v-if="['kimi','zhipu','deepseek'].includes(account?.platform || '')" @click="run('查询 Coding Plan 配额', () => cnProvidersAPI.queryQuota(account!.id))">查询窗口配额</button><button v-if="['kimi','deepseek'].includes(account?.platform || '')" @click="run('查询 PAYG 余额', () => cnProvidersAPI.queryBalance(account!.id))">查询余额</button></div><fieldset v-if="account?.platform === 'openai'" class="resource-form-section"><legend>Spark 影子账号参数</legend><div class="resource-form-grid resource-form-grid--3"><label>名称<input v-model="shadow.name" /></label><label>优先级<input v-model.number="shadow.priority" type="number" /></label><label>并发<input v-model.number="shadow.concurrency" type="number" min="1" /></label></div></fieldset></section>
  <section v-else-if="tab === WorkspaceTab.MODELS" class="resource-form-stack"><div class="resource-inline-actions"><button class="resource-button" @click="loadModels">读取可用模型</button><button class="resource-button resource-button--secondary" @click="run('同步上游模型', () => accountsAPI.syncUpstreamModels(account!.id)).then(loadModels)">同步上游模型</button></div><div class="model-grid"><span v-for="model in models" :key="model.id">{{ model.display_name || model.id }}<small>{{ model.id }}</small></span></div></section>
  <section v-else-if="tab === WorkspaceTab.SCHEDULE" class="resource-form-stack"><fieldset class="resource-form-section"><legend>{{ scheduleForm.id ? '编辑测试计划' : '新建测试计划' }}</legend><div class="resource-form-grid resource-form-grid--3"><label>模型<select v-model="scheduleForm.model_id"><option value="">请选择</option><option v-for="model in models" :key="model.id" :value="model.id">{{ model.display_name || model.id }}</option></select></label><label>Cron<input v-model="scheduleForm.cron_expression" /></label><label>保留结果数<input v-model.number="scheduleForm.max_results" type="number" min="1" /></label><label class="resource-check"><input v-model="scheduleForm.enabled" type="checkbox" /><span>启用</span></label><label class="resource-check"><input v-model="scheduleForm.auto_recover" type="checkbox" /><span>成功后自动恢复</span></label></div><div class="resource-inline-actions"><button class="resource-button" @click="savePlan">保存计划</button><button v-if="scheduleForm.id" class="resource-button resource-button--secondary" @click="resetSchedule">取消编辑</button></div></fieldset><div class="schedule-list"><article v-for="plan in plans" :key="plan.id"><div><strong>{{ plan.model_id }}</strong><small>{{ plan.cron_expression }} · 下次 {{ formatResourceDate(plan.next_run_at) }}</small></div><span :class="['resource-status', plan.enabled ? 'resource-status--active' : '']">{{ plan.enabled ? '启用' : '停用' }}</span><button class="resource-link" @click="editPlan(plan)">编辑</button><button class="resource-link" @click="loadResults(plan)">结果</button><button class="resource-link resource-link--danger" @click="deletePlan(plan)">删除</button><pre v-if="results[plan.id]" class="resource-code">{{ JSON.stringify(results[plan.id], null, 2) }}</pre></article></div></section>
  <section v-else-if="tab === WorkspaceTab.BILLING" class="resource-form-stack"><fieldset class="resource-form-section"><legend>账号上游计费</legend><label class="resource-check"><input v-model="probeEnabled" type="checkbox" @change="toggleProbe" /><span>启用当前账号探测</span></label><div class="action-grid"><button @click="run('上游计费探测', () => accountsAPI.probeUpstreamBilling(account!.id))">立即探测</button></div></fieldset><fieldset class="resource-form-section"><legend>全局探测设置</legend><div class="resource-form-grid"><label class="resource-check"><input v-model="globalProbe.enabled" type="checkbox" /><span>启用全局探测</span></label><label>间隔分钟<input v-model.number="globalProbe.interval_minutes" type="number" min="1" /></label></div><button class="resource-button" @click="saveBillingSettings">保存全局设置</button></fieldset></section>
  <section v-else class="resource-form-stack"><fieldset class="resource-form-section"><legend>当前账号 Session</legend><label>Ollama Cloud Session<textarea v-model="ollamaSession" rows="4" /></label><div class="resource-inline-actions"><button class="resource-button" @click="mutate('保存 Ollama Session', () => accountsAPI.saveOllamaCloudUsageSession(account!.id, ollamaSession), 'Session 已保存')">保存 Session</button><button class="resource-button resource-button--secondary" @click="run('刷新 Ollama 用量', () => accountsAPI.refreshOllamaCloudUsage(account!.id))">刷新用量</button><button class="resource-button resource-button--secondary" @click="mutate('更新 Ollama 自动刷新', () => accountsAPI.setOllamaCloudUsageAutoRefresh(account!.id, !ollamaAuto), '自动刷新已更新').then(() => ollamaAuto = !ollamaAuto)">{{ ollamaAuto ? '关闭' : '开启' }}自动刷新</button><button class="resource-button resource-button--danger" @click="deleteOllamaSession">删除 Session</button></div></fieldset><fieldset class="resource-form-section"><legend>全局 Ollama 刷新策略</legend><div class="resource-form-grid resource-form-grid--3"><label class="resource-check"><input v-model="ollamaSettings.enabled" type="checkbox" /><span>启用</span></label><label>最长等待分钟<input v-model.number="ollamaSettings.interval_minutes" type="number" min="1" /></label><label>静默窗口分钟<input v-model.number="ollamaSettings.debounce_minutes" type="number" min="1" /></label></div><button class="resource-button" @click="saveOllamaSettings">保存全局设置</button></fieldset></section>
  <section v-if="outputText" class="operation-output"><header><strong>{{ outputTitle }}</strong><button class="resource-link" @click="copyOutput">复制结果</button></header><pre class="resource-code">{{ outputText }}</pre></section><p v-if="running" class="muted">正在执行：{{ running }}…</p>
  </div></SurfaceDialog></template>

<style scoped>.action-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; }.action-grid button { min-height: 52px; padding: 9px; color: var(--text-primary); background: var(--surface-canvas); border: 1px solid var(--border-subtle); border-radius: 10px; cursor: pointer; font-weight: 700; }.action-grid button:hover { border-color: var(--accent); }.action-grid .danger { color: var(--danger); }.operation-output { padding: 14px; display: grid; gap: 9px; background: var(--surface-canvas); border-radius: 12px; }.operation-output header { display: flex; justify-content: space-between; }.model-grid { display: flex; flex-wrap: wrap; gap: 7px; }.model-grid span { padding: 8px 10px; display: grid; gap: 3px; background: var(--surface-canvas); border-radius: 8px; }.model-grid small { color: var(--text-secondary); }.schedule-list { display: grid; gap: 7px; }.schedule-list article { padding: 11px; display: grid; grid-template-columns: 1fr auto auto auto auto; align-items: center; gap: 7px; background: var(--surface-canvas); border-radius: 9px; }.schedule-list article > div { display: grid; gap: 4px; }.schedule-list small { color: var(--text-secondary); }.schedule-list pre { grid-column: 1 / -1; } @media(max-width:700px){.action-grid{grid-template-columns:repeat(2,1fr)}.schedule-list article{grid-template-columns:1fr auto}.schedule-list article > div{grid-column:1/-1}}</style>
